### ISSUE TITLE
ToDo LoxBerry V1.0

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#482]
Webseite / Wiki:
- [x] Logos vorbereiten
- [x] Splashscreen (großes Logo) vorbereiten
- [x] Statistik bzw. Statistiken auf loxberry.de
- [x] Wiki Startseite vorbereiten
- [x] Release-Text V1.0 vorbereiten (Forum)
- [x] loxberry.de Startseite vorbereiten
- [x] What's New final überarbeiten - mit Links
- [x] What's New übersetzen (englisch)
- [x] Pluginliste: Kompatibilitäts-Flag in der Tabelle aktivieren - ist schon vorbereitet (--> Christian)
- [x] Wiki-Artikel (V0.3) umreihen
- [x] Alle V0.3 Wiki-Artikel bereinigen und Versionsnummern ändern
- [x] Alle alten/obsoleten Artikel in ein Wiki-Archiv verschieben

Module/Widgets:
- [x] Setup-Wizard
- [x] Logging für Bash fertigstellen
- [ ] Logging für PHP (eher mitliefern)
- [x] Translate für Plugins (eher mitliefern)
- [ ] Notify-Bullets für Plugins (eher nachliefern)
- [x] Notify für PHP (eher nachliefern)

Plugin-Interface V2:
- [x] Automatisches Plugin-Update fertigstellen
- [ ] Doku Wiki
- [ ] Sample-Plugin Perl fertigstellen
- [ ] Sample-Plugin PHP fertigstellen

LoxBerry allgemein:
- [x] Deutsche Übersetzung fertigstellen
- [ ] Hilfe-Template für die Widgets (eher nachliefern)
- [ ] Alte sprachspezifische Templates aufräumen
- [x] LoxBerry Update maxversion anpassen
- [x] Neuer Branch? Muss auch in LoxBerry Update angepasst werden! Wir sollten den Entwicklungszweig bei der Umstellung auf master ändern.
- [ ] Upgrade Plugin?
