### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by christianTF** [mschlenstedt/Loxberry#584]
Hi,
ich habe einen imaginären Milestone 1.1 erzeugt (der nicht implizit ein neues Image bedeuten muss).

Es gibt damit jetzt **1.0**, **1.1** und **Later Future**.

Darin sollten wir entsprechend festlegen, welche Dinge wir wann noch umsetzen wollen.

Das sind die Punkte, die ich auf _meiner_ "Liste" stehen habe. Irgendein Feedback zur Priorisierung oder was überflüssig ist?

- [x] Notifications als SQLite Datenbank
- [x] Notifications für PHP
- [x] Notifications ermöglichen für Plugins
- [x] Notifications auf der Plugins-Seite anzeigen
- [x] Notifications per AJAX statt im Script holen 

- [x] Logging für Perl
- [ ] Zentrales Log Management (ggf. auch SQLite)

- [x] Logging und Notifications mit einer Mail-Funktion 

- [x] Plugin-Updates direkt aus der Plugin-Zeile heraus

**Comment by Woersty** [comment]
Just my 2 cents:
Notifications als SQLite Datenbank => dafür, in 1.0
Notifications für PHP => dafür, in 1.0
Notifications ermöglichen für Plugins => dafür, in 1.0
Notifications auf der Plugins-Seite anzeigen => dafür, in 1.0
Notifications per AJAX statt im Script holen => dafür, in 1.0
Logging für Perl => dafür, in 1.1 oder later
Zentrales Log Management (ggf. auch SQLite) => dafür, in 1.1 oder later
Logging und Notifications mit einer Mail-Funktion => dafür, in 1.1 oder later
Plugin-Updates direkt aus der Plugin-Zeile heraus => #585

**Comment by christianTF** [comment]
Es wäre beispielsweise cool, wenn den Logging-für-PHP Teil jemand übernehmen könnte, dann kann ich mich voll auf die Notifications konzentrieren.
Wörsty und Sven, ihr seid eh zwei PHP-Geeks. 
Sven hat auch schon Erfahrung mit Logging für Bash.

Das ist natürlich ein größeres Projekt. Logging für Perl hab ich auch nicht in einem Tag gebaut (sondern in zwei :stuck_out_tongue_closed_eyes:)

**Comment by svethi** [comment]
Ist doch schon gut. Wir hatten doch schon gesagt das ich das mache.
Problem ist nur die Zeit. Bei uns jagt Anfang des Jahres ein Geburtstag den nächsten

**Comment by christianTF** [comment]
War doch kein Vorwurf!

**Comment by svethi** [comment]
Ich brauch unbedingt mehr Zeit :-) PHP-Logging hätte ich jetzt schon gut gebrauchen können
